languageCode: fr-fr
baseURL: https://dysta.github.io/
title: Dysta's Code Chamber
theme: "PaperMod"
paginate: 5
enableEmoji: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Dysta's Code Chamber
    description: "Dysta's personnal blog."
    keywords: [Blog, Portfolio, PaperMod]
    author: Dysta
    discordInvitCode: "3u3HyEsMah"
    # author: ["Me", "You"] # multiple authors
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    # home-info mode
    homeInfoParams:
        Title: "Salut \U0001F44B"
        Content: "Je suis passionné d'informatique depuis plusieurs années.\n\n

                    Je suis développeur logiciel, diplomé d'un **master**.\n\n

                    Ce que vous trouverez ici ? Un peu de tout : mon CV, des articles sur des techno, ou encore des projets que je suis actuellement en train de mettre en place. En bref, vous êtes dans mon espace personnel ! 😎\n\n
                "

    socialIcons:
        - name: github
          url: "https://github.com/Dysta"
        - name: kofi
          url: "https://ko-fi.com/dysta"
        - name: discord
          url: "https://discord.com/users/845189167914549288"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: CV
          name: Curriculum Vitae
          url: /cv/
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 30
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 40

# search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
